### ISSUE TITLE
Crate does not compile on MacOS

### ISSUE THREAD

**Issue by klausi** [danburkert/procinfo-rs#30]
I specify procinfo in my dev-dependencies because I have a Linux specific memory leak test, see https://github.com/klausi/rustnish/blob/goal-07/tests/memory_leaks.rs

On MacOS I simply skip that test. When compiling my project for cargo test the build fails because procinfo does not compile on MacOS.

Can we make procinfo compile on MacOS although we know it does not work there?

**Comment by klausi** [comment]
OK, nevermind, I just found out about conditional compilation, so I can include this crate and my test only on Linux.
Cargo.toml:
```toml
# Memory Leak tests require procinfo, which only works on Linux.
[target.'cfg(target_os="linux")'.dev-dependencies]
procinfo = ">=0.4.2"
```
Test file:
```rust
// This test uses procinfo, so can only be run on Linux.
#![cfg(target_os = "linux")]
```
